name: Publish Ansible Collection to Galaxy

workflow_dispatcher:
on:
  push:
    tags:
      - "v*"

jobs:
  release-sanity-test:
    uses: ./.github/workflows/sanity.yml

  release:
    name: Publish to Ansible Galaxy
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    needs:
      - release-sanity-test
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
